Added ping.md still creating it h
xf8b/xf8bot pull request #24
Opened 2020-09-28 18:08 UTC by BHLoneWolf0

2020-09-28 18:09 UTC, xf8b commented
closing because it seems like you commited the whole production branch. please refork

2020-09-28 18:15 UTC, xf8b requested changes
no

2020-09-28 18:17 UTC, closed without merging

2020-09-28 18:18 UTC, zAG6z commented
i am so confused

2020-11-24 01:32 UTC, xf8b commented
tl;dr dont merge production with your branch